## Demo script for R burnr package
## Chris Guiterman
## chguiterman@email.arizona.edu
## 2018-5-27

## Module 3: Analyses

library(burnr)
library(ggplot2)

data(pgm)


# Intervals analysis -------------------------------------------------------------

# See some basic stats for each tree (series)
head(series_stats(pgm))

#' Site-level analyses generally require compositing the tree-level data to generate a 
#' single site fire history, or "master chronology"
#' Burnr allows for a multitude of filtering methods in composite()

# Create a composite with all scars
pgm.comp <- composite(pgm, filter_min_events = 1, filter_prop = 0, filter_min_rec = 1,
                      comp_name = 'PGM')
plot(pgm.comp)

## Interval analysis on the composite
intervals(pgm.comp)

#' Note that the warnings are generated by the curve-fitting algorithms (MASS::fitdistr)
#' and we opted to keep them. 

#' The default theoretical fit is a weibull, but log-normal is also available
intervals(pgm.comp, densfun = "lognormal")

# Make it an intervals object and plot the data
pgm_interv <- intervals(pgm.comp)

plot(pgm_interv, binwidth=5)

boxplot(pgm_interv$intervals)

# Check out seasonality
pgm_seasons <- count_event_position(pgm, drop_unknown = TRUE)
print(pgm_seasons)

ggplot(pgm_seasons) + geom_bar(aes(x=event, y=prop), stat='identity')


# Superposed Epoch Analysis -----------------------------------------------

# Read in PDSI timeseries for pgm
data("pgm_pdsi")

#' This PDSI timeseries came from the North American Drought Atlas
#' https://iridl.ldeo.columbia.edu/SOURCES/.LDEO/.TRL/.NADA2004/.pdsi-atlas.html

head(pgm_pdsi)

my_year <- c(1748, 1813, 1822, 1851, 1904)

#' Run SEA with the sea function, and make an object for later visuals
pgm.sea <- sea(x = pgm_pdsi, event = pgm.comp, nbefore = 4, nafter = 2)

#' Basic (and FAST) graphic
plot(pgm.sea)

## Make a nicer, more pub-worthy graphic. This requires some extra functionality
source("R/SEA_Helper_FUNS.R")

pgm_sea_sig <- sea_sig(pgm.sea$departure)

ggplot(pgm_sea_sig, aes(x=lag)) + geom_col(aes(y=mean, fill=sig), width=.7) +
  scale_fill_manual(values=sea_cols, guide="none") + 
  scale_x_continuous(name="Lag year", breaks=seq(-4, 2, 1), labels=seq(-4, 2, 1)) +
  ylab("PDSI departure") +
  geom_line(aes(y=upper_95_perc)) + geom_line(aes(y=lower_95_perc)) + 
  geom_line(aes(y=upper_99_perc), linetype=3) + geom_line(aes(y=lower_99_perc), linetype=3) +
  ylim(-2.5, 2) + theme_bw() +
  theme(panel.grid.minor=element_blank(), axis.text = element_text(size=16), axis.title=element_text(size=18),
        strip.text = element_text(size=11), plot.title=element_text(size=18))
ggsave("Output/PGM_SEA.tiff", device="tiff", width=4, height=4, dpi=300)
